version: '3.8'

name: infra-keycloak

services:
  auth:
    image: bitnami/keycloak:20-debian-11
    healthcheck:
      test: ["CMD", "curl", "--head", "-fsS", "http://localhost:8181/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_HTTP_PORT=8181
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_NAME=${DB_NAME}
      - KEYCLOAK_DATABASE_USER=${DB_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ENABLE_STATISTICS=true
      - KEYCLOAK_LOG_LEVEL=debug
      - KEYCLOAK_EXTRA_ARGS_PREPENDED=${KC_EXTRA_ARGS}
    volumes:
      - "./providers:/opt/bitnami/keycloak/providers"
      - "./themes:/opt/bitnami/keycloak/themes"
    ports:
      - "0.0.0.0:8181:8181"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  db:
    image: bitnami/postgresql:14-debian-11
    healthcheck:
      test: [ "CMD", "pg_isready", "-U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - "postgres_data:/bitnami/postgresql"

  pg_admin:
    image: dpage/pgadmin4:8.3
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - "pgadmin_data:/pgadmin4"
    ports:
      - "5050:5050"
    depends_on:
      - db

  kafka:
    image: bitnami/kafka:3.6.1
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - "kafka_data:/bitnami/kafka"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper_data:/bitnami/zookeeper"

  ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=infra-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
      - zookeeper


volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
